/*
 * NewJFrame2.java
 *
 * Created on April 2, 2009, 7:20 PM
 */

package testcasegenerator;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.util.Arrays;

import java.io.File;
import javax.swing.*;
import java.util.Hashtable;
import java.awt.*;


/**
 *
 * @author  Mehdi
 */
public class AppInterface extends javax.swing.JFrame {

    /** Creates new form NewJFrame2 */
    JLabel a;
    fileContainer[] javaFiles;
    String currentSelectedFile;
    ToBooleanExp test = new ToBooleanExp();
    String[][] causes;              // declares an array of String for read causes in set constraints form
    String[] cons;               // declares an array of Strings for read type of contraint in set constraints form
    int l,m=0;
    JInternalFrame iFrame;
    DrawGraph graph;
  
          
  //  String currentSelectedFile;
    public AppInterface() {
        initComponents();
        initComponents2(); 
        Image im = Toolkit.getDefaultToolkit().getImage("C:\\Documents and Settings\\MEHDIMZ\\My Documents\\NetBeansProjects\\Logo for testig Tools\\big-logo.png");
        setIconImage(im);  // set icon for main frame
        causes = new String[3][3];
        cons=new String[3];
        jInternalFrame_Newproject.setDefaultCloseOperation(jInternalFrame_Newproject.DISPOSE_ON_CLOSE);
    }
    
    private void initComponents2() {
       // throw new UnsupportedOperationException("Not yet implemented");
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automatic TestCase Generator v1.0");
         
       // PanelLeft.setBackground(new java.awt.Color(255, 255, 255));  
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Specification = new javax.swing.JInternalFrame();
        jPanel_Left = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPanesource_code = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Effect = new javax.swing.JLabel();
        jLabel_Causes = new javax.swing.JLabel();
        jLabel_BooleanExp = new javax.swing.JLabel();
        jLabel_constraint = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_PrjName = new javax.swing.JLabel();
        jPanel_Right = new javax.swing.JPanel();
        jScrollMonitor = new javax.swing.JScrollPane();
        PanelMonitor = new javax.swing.JPanel();
        jInternalFrame_Newproject = new javax.swing.JInternalFrame();
        jPanel_NewPrj = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton_Next = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton_Browse = new javax.swing.JButton();
        jPanel_SetConstraint = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton_Exclusive = new javax.swing.JRadioButton();
        jRadioButton_Inclusive = new javax.swing.JRadioButton();
        jRadioButton_OnlyOne = new javax.swing.JRadioButton();
        jTextField_C1 = new javax.swing.JTextField();
        jTextField_C2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel_EditBooleanExp = new javax.swing.JPanel();
        jTextField_BooleanExp = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel_CE_Table = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_CE_Table = new javax.swing.JTextPane();
        jPanel_TestCases = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane_TestCases = new javax.swing.JScrollPane();
        jTextPane_GTestCases = new javax.swing.JTextPane();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_NewPrj = new javax.swing.JMenuItem();
        jMenuItem_SaveGraph = new javax.swing.JMenuItem();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu_Actions = new javax.swing.JMenu();
        jMenuItem_EditBooleanExp = new javax.swing.JMenuItem();
        jMenuItem_SetConstraint = new javax.swing.JMenuItem();
        jMenuItem_Produce_CE_Table = new javax.swing.JMenuItem();
        jMenuItem_DrawCEG = new javax.swing.JMenuItem();
        jMenuItem_GenerateTestCase = new javax.swing.JMenuItem();
        jMenu_About = new javax.swing.JMenu();
        jMenuItem_About = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Specification.setClosable(true);
        Specification.setIconifiable(true);
        Specification.setResizable(true);
        Specification.setTitle("Read Specification of System");
        Specification.setMinimumSize(new java.awt.Dimension(500, 600));
        Specification.setPreferredSize(new java.awt.Dimension(900, 650));
        try {
            Specification.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        Specification.setVisible(true);

        jPanel_Left.setBackground(new java.awt.Color(242, 242, 225));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Specifications");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(jTextPanesource_code);

        jPanel1.setBackground(new java.awt.Color(9, 113, 113));

        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Effect:");

        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Number of Causes:");

        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Related Boolean Expression:");

        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Constraint:");

        jLabel_Effect.setForeground(new java.awt.Color(255, 102, 0));
        jLabel_Effect.setText("jLabel8");

        jLabel_Causes.setForeground(new java.awt.Color(153, 255, 153));
        jLabel_Causes.setText("jLabel9");

        jLabel_BooleanExp.setForeground(new java.awt.Color(255, 255, 153));
        jLabel_BooleanExp.setText("jLabel10");

        jLabel_constraint.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_constraint, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_BooleanExp, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Effect, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Causes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_Effect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_Causes))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_BooleanExp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_constraint, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jLabel17.setForeground(new java.awt.Color(204, 0, 102));
        jLabel17.setText("jLabel15");

        jLabel_PrjName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_PrjName.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel_LeftLayout = new javax.swing.GroupLayout(jPanel_Left);
        jPanel_Left.setLayout(jPanel_LeftLayout);
        jPanel_LeftLayout.setHorizontalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftLayout.createSequentialGroup()
                .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)))
                    .addGroup(jPanel_LeftLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel_PrjName, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_LeftLayout.setVerticalGroup(
            jPanel_LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LeftLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel_PrjName)
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jPanel_Right.setBackground(new java.awt.Color(242, 242, 225));

        PanelMonitor.setBackground(new java.awt.Color(93, 88, 57));

        javax.swing.GroupLayout PanelMonitorLayout = new javax.swing.GroupLayout(PanelMonitor);
        PanelMonitor.setLayout(PanelMonitorLayout);
        PanelMonitorLayout.setHorizontalGroup(
            PanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        PanelMonitorLayout.setVerticalGroup(
            PanelMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );

        jScrollMonitor.setViewportView(PanelMonitor);

        javax.swing.GroupLayout jPanel_RightLayout = new javax.swing.GroupLayout(jPanel_Right);
        jPanel_Right.setLayout(jPanel_RightLayout);
        jPanel_RightLayout.setHorizontalGroup(
            jPanel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );
        jPanel_RightLayout.setVerticalGroup(
            jPanel_RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RightLayout.createSequentialGroup()
                .addComponent(jScrollMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SpecificationLayout = new javax.swing.GroupLayout(Specification.getContentPane());
        Specification.getContentPane().setLayout(SpecificationLayout);
        SpecificationLayout.setHorizontalGroup(
            SpecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SpecificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SpecificationLayout.setVerticalGroup(
            SpecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecificationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SpecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jInternalFrame_Newproject.setClosable(true);
        jInternalFrame_Newproject.setIconifiable(true);
        jInternalFrame_Newproject.setTitle("Create New Project");
        jInternalFrame_Newproject.setLayer(3);
        jInternalFrame_Newproject.setVisible(true);

        jPanel_NewPrj.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("Please Define New Software Project");

        jLabel12.setForeground(new java.awt.Color(249, 249, 194));
        jLabel12.setText("Name of Critical Software System:");

        jLabel13.setForeground(new java.awt.Color(249, 249, 194));
        jLabel13.setText("Critical Specification File:");

        jLabel14.setForeground(new java.awt.Color(249, 249, 194));
        jLabel14.setText("Critical Part:");

        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });

        jTextField2.setForeground(new java.awt.Color(51, 102, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setForeground(new java.awt.Color(0, 0, 255));

        jTextField4.setForeground(new java.awt.Color(51, 51, 255));

        jButton_Browse.setText("Browse");
        jButton_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NewPrjLayout = new javax.swing.GroupLayout(jPanel_NewPrj);
        jPanel_NewPrj.setLayout(jPanel_NewPrjLayout);
        jPanel_NewPrjLayout.setHorizontalGroup(
            jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NewPrjLayout.createSequentialGroup()
                .addGroup(jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NewPrjLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_NewPrjLayout.createSequentialGroup()
                                .addGroup(jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Browse))))
                    .addGroup(jPanel_NewPrjLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel_NewPrjLayout.setVerticalGroup(
            jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NewPrjLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel_NewPrjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Browse))
                .addGap(55, 55, 55)
                .addComponent(jButton_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame_NewprojectLayout = new javax.swing.GroupLayout(jInternalFrame_Newproject.getContentPane());
        jInternalFrame_Newproject.getContentPane().setLayout(jInternalFrame_NewprojectLayout);
        jInternalFrame_NewprojectLayout.setHorizontalGroup(
            jInternalFrame_NewprojectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_NewprojectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_NewPrj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jInternalFrame_NewprojectLayout.setVerticalGroup(
            jInternalFrame_NewprojectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_NewprojectLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel_NewPrj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(867, Short.MAX_VALUE))
        );

        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Cause 1");

        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Cause 2");

        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Cause 3");

        jRadioButton_Exclusive.setText("Exclusive");
        jRadioButton_Exclusive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ExclusiveActionPerformed(evt);
            }
        });

        jRadioButton_Inclusive.setText("Inclusive");
        jRadioButton_Inclusive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_InclusiveActionPerformed(evt);
            }
        });

        jRadioButton_OnlyOne.setText("One and Only One");
        jRadioButton_OnlyOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_OnlyOneActionPerformed(evt);
            }
        });

        jTextField_C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_C1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Select Type of Constraint:");

        javax.swing.GroupLayout jPanel_SetConstraintLayout = new javax.swing.GroupLayout(jPanel_SetConstraint);
        jPanel_SetConstraint.setLayout(jPanel_SetConstraintLayout);
        jPanel_SetConstraintLayout.setHorizontalGroup(
            jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SetConstraintLayout.createSequentialGroup()
                .addGroup(jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_SetConstraintLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jTextField_C2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jTextField_C1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_SetConstraintLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton_Exclusive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton_Inclusive)))
                .addGap(2, 2, 2)
                .addComponent(jRadioButton_OnlyOne)
                .addGap(34, 34, 34))
            .addGroup(jPanel_SetConstraintLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel_SetConstraintLayout.setVerticalGroup(
            jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SetConstraintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SetConstraintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Exclusive)
                    .addComponent(jRadioButton_Inclusive)
                    .addComponent(jRadioButton_OnlyOne))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel16.setForeground(new java.awt.Color(102, 0, 0));
        jLabel16.setText("Boolean Expression:");

        javax.swing.GroupLayout jPanel_EditBooleanExpLayout = new javax.swing.GroupLayout(jPanel_EditBooleanExp);
        jPanel_EditBooleanExp.setLayout(jPanel_EditBooleanExpLayout);
        jPanel_EditBooleanExpLayout.setHorizontalGroup(
            jPanel_EditBooleanExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EditBooleanExpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_EditBooleanExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_EditBooleanExpLayout.createSequentialGroup()
                        .addComponent(jTextField_BooleanExp, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_EditBooleanExpLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))))
        );
        jPanel_EditBooleanExpLayout.setVerticalGroup(
            jPanel_EditBooleanExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EditBooleanExpLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_BooleanExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setText("Cause-Effect Table");

        jTextPane_CE_Table.setBackground(new java.awt.Color(247, 247, 218));
        jTextPane_CE_Table.setEditable(false);
        jTextPane_CE_Table.setForeground(new java.awt.Color(102, 0, 0));
        jScrollPane2.setViewportView(jTextPane_CE_Table);

        javax.swing.GroupLayout jPanel_CE_TableLayout = new javax.swing.GroupLayout(jPanel_CE_Table);
        jPanel_CE_Table.setLayout(jPanel_CE_TableLayout);
        jPanel_CE_TableLayout.setHorizontalGroup(
            jPanel_CE_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CE_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CE_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_CE_TableLayout.setVerticalGroup(
            jPanel_CE_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CE_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel19.setForeground(new java.awt.Color(102, 0, 0));
        jLabel19.setText("TestCases:(T=True,F=False)");

        jTextPane_GTestCases.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane_TestCases.setViewportView(jTextPane_GTestCases);

        javax.swing.GroupLayout jPanel_TestCasesLayout = new javax.swing.GroupLayout(jPanel_TestCases);
        jPanel_TestCases.setLayout(jPanel_TestCasesLayout);
        jPanel_TestCasesLayout.setHorizontalGroup(
            jPanel_TestCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TestCasesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_TestCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_TestCases, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TestCasesLayout.setVerticalGroup(
            jPanel_TestCasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TestCasesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_TestCases, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu_File.setText("File");

        jMenuItem_NewPrj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_NewPrj.setText("New Project");
        jMenuItem_NewPrj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_NewPrjActionPerformed1(evt);
            }
        });
        jMenu_File.add(jMenuItem_NewPrj);

        jMenuItem_SaveGraph.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_SaveGraph.setText("Save Graph as Image");
        jMenuItem_SaveGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_SaveGraph);

        jMenuItem_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Exit.setText("Exit");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Exit);

        jMenuBar4.add(jMenu_File);

        jMenu_Actions.setText("Actions");

        jMenuItem_EditBooleanExp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_EditBooleanExp.setText("Edit Boolean Expression");
        jMenuItem_EditBooleanExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_EditBooleanExpActionPerformed(evt);
            }
        });
        jMenu_Actions.add(jMenuItem_EditBooleanExp);

        jMenuItem_SetConstraint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_SetConstraint.setText("Set Constraints");
        jMenuItem_SetConstraint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SetConstraintActionPerformed1(evt);
            }
        });
        jMenu_Actions.add(jMenuItem_SetConstraint);

        jMenuItem_Produce_CE_Table.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Produce_CE_Table.setText("Produce Cause-Effect Table");
        jMenuItem_Produce_CE_Table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Produce_CE_TableActionPerformed(evt);
            }
        });
        jMenu_Actions.add(jMenuItem_Produce_CE_Table);

        jMenuItem_DrawCEG.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_DrawCEG.setText("Draw Cause-Effcet Graph");
        jMenuItem_DrawCEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DrawCEGActionPerformed(evt);
            }
        });
        jMenu_Actions.add(jMenuItem_DrawCEG);

        jMenuItem_GenerateTestCase.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_GenerateTestCase.setText("Generate TestCases");
        jMenuItem_GenerateTestCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GenerateTestCaseActionPerformed1(evt);
            }
        });
        jMenu_Actions.add(jMenuItem_GenerateTestCase);

        jMenuBar4.add(jMenu_Actions);

        jMenu_About.setText("About");

        jMenuItem_About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_About.setText("About");
        jMenuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AboutActionPerformed1(evt);
            }
        });
        jMenu_About.add(jMenuItem_About);

        jMenuBar4.add(jMenu_About);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jInternalFrame_Newproject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(Specification, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                    .addGap(49, 49, 49)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(266, 266, 266)
                    .addComponent(jPanel_SetConstraint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(614, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(415, 415, 415)
                    .addComponent(jPanel_EditBooleanExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jPanel_CE_Table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jPanel_TestCases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jInternalFrame_Newproject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(631, Short.MAX_VALUE)
                    .addComponent(Specification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(206, 206, 206)
                    .addComponent(jPanel_SetConstraint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(897, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(494, 494, 494)
                    .addComponent(jPanel_EditBooleanExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(734, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(jPanel_CE_Table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(694, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jPanel_TestCases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(603, 603, 603)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    
    //selecting the files and creating fileContainer objects and store them in the javaFiles array

      
       
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
    this.dispose();
    Specification.dispose();
    jInternalFrame_Newproject.dispose();
    
 //   setDefaultCloseOperation(ABORT);
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem_EditBooleanExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_EditBooleanExpActionPerformed
// TODO add your handling code here:
    
    
    JFrame frame = new JFrame("Edit Boolean Expression");

        frame.setUndecorated( true );
        frame.setVisible( true );
        frame.setLocationRelativeTo( null );       
        jTextField_BooleanExp.setText(test.BooleanExp);
        
  int a=JOptionPane.showConfirmDialog(frame,jPanel_EditBooleanExp,"Edit Boolean Expression",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);  
  //Operation that will do when user click 'OK'  
  if(a==JOptionPane.OK_OPTION)  
    {  
  
  
      test.BooleanExp=jTextField_BooleanExp.getText(); 
      jLabel_BooleanExp.setText(test.BooleanExp);    
      Specification.updateUI();
      Specification.setVisible(true);
      System.out.println(test.BooleanExp);
  }  //end if 
   
 
     
      frame.dispose();
                       
}//GEN-LAST:event_jMenuItem_EditBooleanExpActionPerformed

    @SuppressWarnings("static-access")
private void jMenuItem_NewPrjActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_NewPrjActionPerformed1
// TODO add your handling code here:
       
                /*        Container content = getContentPane();
                        content.doLayout();
                        jInternalFrame_Newproject.setBounds(80, 55, 680, 400);
                        content.add(jInternalFrame_Newproject); */
                        
                        
                        
 
        JLayeredPane pane = getLayeredPane();
        pane.setOpaque(true);
        addInternalFrame("Create New Project", 130, 100,670,400, JLayeredPane.DEFAULT_LAYER, Color.CYAN,jPanel_NewPrj);
        
        
        //Clear Variables for new project
        test.BooleanExp="";
        test.CauseTable.clear();
        test.Effect="";
        test.j=0; 
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");

        
        

        
        l=0; 
}//GEN-LAST:event_jMenuItem_NewPrjActionPerformed1

private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NextActionPerformed
// TODO add your handling code here:
    
                  causes[0][0]=null;
                  causes[0][1]=null;
                  causes[1][0]=null;
                  causes[1][1]=null;
                  cons[0]=null;
                  cons[1]=null;
                  jLabel_constraint.setText(""); 
                        
                  
                        addInternalFrame_1("Read Specifications of System", 1, 21,1015,700, JLayeredPane.PALETTE_LAYER, Color.MAGENTA,jPanel_Left,jPanel_Right);
                  
                        String s=jTextField2.getText();
                        String s1=jTextField3.getText();
                        jLabel_PrjName.setText(s+" - "+s1);
                        jLabel_Effect.setText(test.Effect);
                        int j=test.j;
                        jLabel_Causes.setText(Integer.toString(j));
                        jLabel_BooleanExp.setText(test.BooleanExp);
                        
                        
                       
                        
                        
                        s="";
                        s1="";
               
                       
    
        
}//GEN-LAST:event_jButton_NextActionPerformed

private void jButton_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseActionPerformed
        try {
// TODO add your handling code here:
            //selecting the files and creating fileContainer objects and store them in the javaFiles array
            JFileChooser fc = new JFileChooser();
            fc.setMultiSelectionEnabled(true);
            fc.showOpenDialog(this);
            File[] selectedFiles = fc.getSelectedFiles();

           
            test.convertToBooleanExp(selectedFiles[0].getAbsolutePath());
            System.out.println(test.BooleanExp);
            System.out.println(test.Effect);

            if (selectedFiles != null) {

                this.javaFiles = new fileContainer[selectedFiles.length];

                //set CurrentSelectedFile for the First Time
                this.currentSelectedFile = selectedFiles[0].getAbsolutePath();

                //empty combo box
                //       this.jTextField4.removeAll();
                for (int i = 0; i < selectedFiles.length; i++) {
                    this.javaFiles[i] = new fileContainer(selectedFiles[i].getAbsolutePath());
                    this.jTextField4.setText(selectedFiles[i].getAbsolutePath());
                    System.out.println(selectedFiles[i].getAbsolutePath());
                }

                initiatingInterface();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AppInterface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AppInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        


}//GEN-LAST:event_jButton_BrowseActionPerformed

private void jMenuItem_SetConstraintActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SetConstraintActionPerformed1
// TODO add your handling code here:
    String s3="";
    l=0;
    JFrame frame=new JFrame("Two text component in JOptionPane");  
   
//Set default close operation for JFrame  
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
   
 
  
  //Set JFrame locate at center  
            frame.setUndecorated( true );

 frame.setLocationRelativeTo(null);    
 //Make JFrame visible  
  frame.setVisible(true);  



  //Show JOptionPane that will ask user for username and password  
  int a=JOptionPane.showConfirmDialog(frame,jPanel_SetConstraint,"Set Constraint",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);  
  //Operation that will do when user click 'OK'  
  if(a==JOptionPane.OK_OPTION)  
  {  
      System.out.println(l);

   //save  constraints and type of them in array
  causes[l][0]=(jTextField_C1.getText()); 
  causes[l][1]=(jTextField_C2.getText()); 
 // cons[l]=jRadioButton_Exclusive.getActionCommand();
  
      if(jRadioButton_Exclusive.isSelected())
      
          cons[l]=jRadioButton_Exclusive.getActionCommand();  
      
          else 
                
              if(jRadioButton_Inclusive.isSelected())
                
                 cons[l]=jRadioButton_Inclusive.getActionCommand();
                  
          else
                 cons[l]=jRadioButton_OnlyOne.getActionCommand();  
                
              
     
                          
  l++;

     Specification.updateUI();
     Specification.setVisible(true);
   
  }  //end if 
   
  for (int i=0;i<l;i++)
                          
                        {
                        if (cons[i]!=null)  
                        s3=s3+causes[i][0]+","+causes[i][1]+"( "+cons[i]+" )"+" ; ";  
                       jLabel_constraint.setText(s3);
                 
                        }
        
  
  
        for (int i=0;i<l;i++)
                          
                        {
                       
                        System.out.println(causes[i][0]+","+causes[i][1]+"\n");
                        } 
     
      frame.dispose();

      
}//GEN-LAST:event_jMenuItem_SetConstraintActionPerformed1

private void jRadioButton_InclusiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_InclusiveActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton_InclusiveActionPerformed

private void jRadioButton_OnlyOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_OnlyOneActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButton_OnlyOneActionPerformed

private void jMenuItem_Produce_CE_TableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Produce_CE_TableActionPerformed

    // TODO add your handling code here:
    //show Cause Effect Table 
    
    String linesShown="";
    for(int i=0;i<test.CauseTable.size();i++)
    {
        
        System.out.println(test.variables[i]+" "+test.CauseTable.get(test.variables[i]));
        
    }
     
    
     JFrame frame = new JFrame("Produce Cause-Effect Table");

        frame.setUndecorated( true );
        frame.setVisible( true );
        frame.setLocationRelativeTo( null );       
     //   jTextPane_CE_Table.setBackground(Color.YELLOW);
        
        jTextPane_CE_Table.setText(" "+"   NO  "+"           "+"   VARIABLE  "+"                                           "+"CAUSE"+"\t\t"+"                          "+"\n");
        
         for(int i=0;i<test.CauseTable.size();i++){
                   
                    String aLine = "\n\n"+"      " + i + "\t          " + test.variables[i]+"\t\t "+test.CauseTable.get(test.variables[i]);
        
                    linesShown = this.jTextPane_CE_Table.getText();
                    linesShown += aLine;
                    jTextPane_CE_Table.setText(linesShown);        
                            
                }
        
        jTextPane_CE_Table.setText(linesShown+"\n\n\n"+"EFFECT : "+test.Effect); 
        
        
        
  int a=JOptionPane.showConfirmDialog(frame,jPanel_CE_Table,"Cause-Effect Table",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);  
  //Operation that will do when user click 'OK'  
  if(a==JOptionPane.OK_OPTION)  
    {  
  
  
      
  }  //end if 
   
 
     
      frame.dispose();
                       
    
    
    
    
    
    
    
    
    
    
}//GEN-LAST:event_jMenuItem_Produce_CE_TableActionPerformed

private void jMenuItem_DrawCEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DrawCEGActionPerformed
// TODO add your handling code here:
    InToPost theTrans = new InToPost(test.BooleanExp);
    String output = theTrans.doTrans(); // convert Infix Exp to Postfix
    System.out.println("Infix is " + test.BooleanExp + '\n'); 
    System.out.println("Postfix is " + output + '\n');  
    String ss=jTextField2.getText()+" - "+jTextField3.getText();
    DrawGraph graph = new DrawGraph(output,causes,l,ss);   //Draw graph from Postfix Exp-cuases is set of constraints,l is a numbers of set of constraints,,ss is a name of project
    
     System.out.println("n=" + graph.n + '\n');
    graph.doTrans(); 
    
}//GEN-LAST:event_jMenuItem_DrawCEGActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

private void jMenuItem_GenerateTestCaseActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GenerateTestCaseActionPerformed1
// TODO add your handling code here:
    int counter=1;
    String linesShown="",Stringvalue_T="",Stringvalue_F="",s="";
    InToPost theTrans = new InToPost(test.BooleanExp);
    String output = theTrans.doTrans(); // convert Infix Exp to Postfix
    CTestCase t = new CTestCase(output);
    t.doTrans(); //Generate TestCases
    System.out.println("True:" + t.TestCases_T + '\n');
    System.out.println("False:" + t.TestCases_F + '\n');
    
    
     JFrame frame = new JFrame("Generate TestCases");

        frame.setUndecorated( true );
        frame.setVisible( true );
        frame.setLocationRelativeTo( null );       
     //   jTextPane_CE_Table.setBackground(Color.YELLOW);
        
       jTextPane_GTestCases.setText(" "+" No."+"\t"); 
        for(int i=0;i<test.CauseTable.size();i++){
                   
                    String aLine = test.variables[i]+"\t";
        
                    linesShown = this.jTextPane_GTestCases.getText();
                    linesShown += aLine;
                    jTextPane_GTestCases.setText(linesShown);       
                            
                } 
        jTextPane_GTestCases.setText(linesShown+"    Result"+"\n\n"+"  "+counter+"\t");
        
        
        
        
        //Delete Testcases(True) that they are not compatible with Constraintes//
        
         for (int j = 0; j < t.TestCases_T .length(); j++) {
           char ch = t.TestCases_T .charAt(j);

            if (ch!=',')
            
                     s = s+ch;
                                 
            else 
                
                 if (checktestcase(s))
                 {
                      Stringvalue_T=Stringvalue_T+s+",";
                      s="";}//end if
                 else s="";
           }//end for
        
        if (checktestcase(s))
                 {
                      Stringvalue_T=Stringvalue_T+s;
                      s="";}
        
        
        
        
        //Delete Testcases(False) that they are not compatible with Constraintes//
        
         for (int j = 0; j < t.TestCases_F .length(); j++) {
           char ch = t.TestCases_F .charAt(j);

            if (ch!=',')
            
                     s = s+ch;
                                 
            else 
                
                 if (checktestcase(s))
                 {
                      Stringvalue_F=Stringvalue_F+s+",";
                      s="";}//end if
                 else s="";
           }//end for
        
        if (checktestcase(s))
                 {
                      Stringvalue_F=Stringvalue_F+s;
                      s="";}
 
        
        
        
        System.out.println("True:" + Stringvalue_T + '\n');
        System.out.println("False:" + Stringvalue_F + '\n');
        
        
        
        //Print True Test Cases// 
        
        for (int j = 0; j < Stringvalue_T .length(); j++) {
          char ch = Stringvalue_T.charAt(j);

            if (ch!=','){
            
                    String value = ch+"\t";
        
                    linesShown = this.jTextPane_GTestCases.getText();
                    linesShown += value;
                    jTextPane_GTestCases.setText(linesShown);
       
        
                }//end if
     
              else{
        
                counter++;
                jTextPane_GTestCases.setText(linesShown+"     T"+"\n\n"+"  "+counter+"\t");             
                } //end else
          
           }//end for
          counter++;
          linesShown = this.jTextPane_GTestCases.getText();
          jTextPane_GTestCases.setText(linesShown+"     T"+"\n\n"+"  "+counter+"\t");
          
          
          //Print False Test Cases //
          
          for (int j = 0; j < Stringvalue_F .length(); j++) {
          char ch = Stringvalue_F.charAt(j);

            if (ch!=','){
            
                    String value = ch+"\t";
        
                    linesShown = this.jTextPane_GTestCases.getText();
                    linesShown += value;
                    jTextPane_GTestCases.setText(linesShown);
       
        
                }//end if
     
              else{
        
                counter++;
                jTextPane_GTestCases.setText(linesShown+"     F"+"\n\n"+"  "+counter+"\t");             
                } //end else
          
           }//end for
          counter++;
          linesShown = this.jTextPane_GTestCases.getText();
          jTextPane_GTestCases.setText(linesShown+"     F");
          
          
          
          
          
          
          
          
          int a=JOptionPane.showConfirmDialog(frame,jPanel_TestCases,"Generate TestCases",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);  

    frame.dispose();
}//GEN-LAST:event_jMenuItem_GenerateTestCaseActionPerformed1

private void jMenuItem_AboutActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AboutActionPerformed1
// TODO add your handling code here:
    
    About info =  new About();
    info.setBounds(375, 250, 425, 250);
    info.setVisible(true);
}//GEN-LAST:event_jMenuItem_AboutActionPerformed1

private void jRadioButton_ExclusiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ExclusiveActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton_ExclusiveActionPerformed

private void jTextField_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_C1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField_C1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMonitor;
    private javax.swing.JInternalFrame Specification;
    private javax.swing.JButton jButton_Browse;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JInternalFrame jInternalFrame_Newproject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_BooleanExp;
    private javax.swing.JLabel jLabel_Causes;
    private javax.swing.JLabel jLabel_Effect;
    private javax.swing.JLabel jLabel_PrjName;
    private javax.swing.JLabel jLabel_constraint;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem_About;
    private javax.swing.JMenuItem jMenuItem_DrawCEG;
    private javax.swing.JMenuItem jMenuItem_EditBooleanExp;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_GenerateTestCase;
    private javax.swing.JMenuItem jMenuItem_NewPrj;
    private javax.swing.JMenuItem jMenuItem_Produce_CE_Table;
    private javax.swing.JMenuItem jMenuItem_SaveGraph;
    private javax.swing.JMenuItem jMenuItem_SetConstraint;
    private javax.swing.JMenu jMenu_About;
    private javax.swing.JMenu jMenu_Actions;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_CE_Table;
    private javax.swing.JPanel jPanel_EditBooleanExp;
    private javax.swing.JPanel jPanel_Left;
    private javax.swing.JPanel jPanel_NewPrj;
    private javax.swing.JPanel jPanel_Right;
    private javax.swing.JPanel jPanel_SetConstraint;
    private javax.swing.JPanel jPanel_TestCases;
    private javax.swing.JRadioButton jRadioButton_Exclusive;
    private javax.swing.JRadioButton jRadioButton_Inclusive;
    private javax.swing.JRadioButton jRadioButton_OnlyOne;
    private javax.swing.JScrollPane jScrollMonitor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_TestCases;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField_BooleanExp;
    private javax.swing.JTextField jTextField_C1;
    private javax.swing.JTextField jTextField_C2;
    private javax.swing.JTextPane jTextPane_CE_Table;
    private javax.swing.JTextPane jTextPane_GTestCases;
    private javax.swing.JTextPane jTextPanesource_code;
    // End of variables declaration//GEN-END:variables


    
    
    
    public boolean checktestcase(String testcase)//check testcase for constraint
            
     {       
        String tc=testcase;
        boolean s = true;
        for (int i=0;i<l;i++)
                          
                        {
                         char ch=tc.charAt(test.findVariablePosition(causes[i][0])); 
                         char ch1= tc.charAt(test.findVariablePosition(causes[i][1]));
                   
                        if (ch==ch1)
                            if (ch=='T')
                               s=false;
                        else
                             s=true;
                      
                        }   // end for
        
        return s;
            
     }    
    
    
    private void addInternalFrame(String name, int x, int y,int x1,int y1, Integer level, Color background,Component comp) {
        JInternalFrame iFrame = new JInternalFrame(name, true, true, true, true);
        iFrame.setBounds(x, y, x1, y1);
  //      iFrame.setBackground(background);
        iFrame.add(comp);
        iFrame.setVisible(true);
        
        int onTop = 1;
        getLayeredPane().add(iFrame, level, onTop);
    }     
    
    
    private void addInternalFrame_1(String name, int x, int y,int x1,int y1, Integer level, Color background,Component comp,Component comp1) {
        JInternalFrame iFrame = new JInternalFrame(name, true, true, true, true);
        iFrame.setBounds(x, y, x1, y1);
  //      iFrame.setBackground(background);
        iFrame.add(comp);
        iFrame.add(comp1);
        iFrame.setVisible(true);
        
        int onTop = 1;
        getLayeredPane().add(iFrame, level, onTop);
    }  
    
    
    
    private void initiatingInterface(){
        
        
        for(int i=0; i<this.javaFiles.length; i++){
            if(this.javaFiles[i].getFilePath().equals(this.currentSelectedFile)){
                //select the object from array based on the currently selected file
                fileContainer tempFile = this.javaFiles[i];
                    
                //populate the text area with code of the current selected file
                this.jTextPanesource_code.setText("");
                Hashtable<Integer, Object[]> tempTable = tempFile.getTableLines();
      
                for(int j=1; j<= tempTable.size(); j++){
                    Object[] lineAndType = tempTable.get(j);
                    String aLineOfCode = "\n" + j + "  : " + lineAndType[0].toString();
                    String linesShown = this.jTextPanesource_code.getText();
                    linesShown += aLineOfCode;
                    this.jTextPanesource_code.setText(linesShown);
                }
                
               
                break;
           }
        
       }
   }
    
  
}
